- hosts: masters[0]
  tasks:

  # Add all users to their respective group.
  - include_tasks: tasks/users-group.yml

  # Label users with their primary-group.
  - include_tasks: tasks/label-users-primary-group.yml
    vars:
      group_priority:
      - users
      - paas-engineers
      - admins

  # Set quota for primary-group=users
  - include_tasks: tasks/set-cluster-quota-by-primary-group.yml
    vars:
      primary_group: users
      quota:
        hard:
          pods: "4"
          requests.cpu: "1"
          requests.memory: "1Gi"
          limits.memory: "1Gi"
          requests.storage: "2Gi"
          limits.ephemeral-storage: "2Gi"

  # Set quota for primary-group=paas-engineers
  - include_tasks: tasks/set-cluster-quota-by-primary-group.yml
    vars:
      primary_group: paas-engineers
      quota:
        hard:
          pods: "4"
          requests.cpu: "1"
          requests.memory: "2Gi"
          limits.memory: "2Gi"
          requests.storage: "4Gi"
          limits.ephemeral-storage: "2Gi"

  # Set quota for primary-group=admins
  - include_tasks: tasks/set-cluster-quota-by-primary-group.yml
    vars:
      primary_group: admins
      quota:
        hard:
          requests.cpu: "2"
          requests.memory: "4Gi"
          limits.memory: "4Gi"
          requests.storage: "10Gi"

  # Adjust limit ranges for sandbox projects as needed.
  - include_tasks: tasks/set-sandbox-limitranges.yml
    vars:
      limitrange:
        spec: "{{ default_project_limitrange_spec }}"
